### ISSUE TITLE
Clean-up touch screen code

### ISSUE THREAD

**Issue by Sebazzz** [CR6Community/Marlin#1]
The touch screen code is a mess currently:

- Switching between languages is sprinkled throughout the source
- There is one big switch to handle events from the touch UI

**Comment by Sebazzz** [comment]
Support for Chinese is dropped. The giant switch for event handling still needs love.

**Comment by Sebazzz** [comment]
@JonBradbury @njoythegame I've been looking though the Marlin sources and there is already stuff in place to communicate with DGUS displays:

https://github.com/Sebazzz/Marlin/tree/creality-cr6-merge-attempt/Marlin/src/lcd/extui/lib/dgus
https://github.com/Sebazzz/Marlin/blob/creality-cr6-merge-attempt/Marlin/src/lcd/extui/dgus_lcd.cpp

I think this can be basis for re-implementing the Creality LCD interfacing code. It is essentially many event handlers for all things that happen in Marlin.

This is the API: https://github.com/Sebazzz/Marlin/blob/creality-cr6-merge-attempt/Marlin/src/lcd/extui/ui_api.h

**Comment by Sebazzz** [comment]
I've been looking into using this as a basis, but the ExtUI implementation for DGUS is quite opinionated:

- In the SD file list you should scroll
- Only one file list instead of five fixed pages
- No separate print status screen for paused / running print

We can adapt the touch screen to use this, but I think for now this is a bridge too far as that would need non-trivial changes to the touch screen. I would rather not do that at the moment because we're also still trying to get basic functions working, the touch screen configuration is all binary and unmergable, so it is best not to deviate too much from mainline.

**Comment by Sebazzz** [comment]
@JonBradbury: I did a write-up here: https://discord.com/channels/759603746270609428/759605549305692170/759870235838251008

I think this might be a viable way to continue.

**Comment by chriskoups** [comment]
Can you share the discord link?

**Comment by Sebazzz** [comment]
Clean up happened in extui.

Ready for next release.

**Comment by Sebazzz** [comment]
@chriskoups Sorry - this: https://discord.gg/zzrBay73
