### ISSUE TITLE
Starts print without reaching target temperature

### ISSUE THREAD

**Issue by frenck** [CR6Community/Marlin#101]
### Description

Running beta 5 pre-release 2 (28 dec).

Starting a print, it homes X, Y & Z. Let's say, I'm running PETG @ 235C nozzle temp.
The following happens:

- Printer heats nozzle to 235C (and bed of course) and waits until it reached that.
- It homes X, Y & Z, during this, it stops heating the nozzle (newly introduced for more accurate measurement).
- After homing, it immediately starts the print, however, the nozzle had cooled down to ~210C in my case in the meantime...

### Steps to Reproduce

See description.

**Expected behavior:** 

The printer to wait until the bed and nozzle to have reached the target temperature, before actually starting to extrude any filament.

**Actual behavior:** 

Starts printing with PETG @ ~210C in my above-described example/case.

**Logging:**

None made.

### Additional Information

Mainboard: BTT CR-6 v1.0
Display: BTT TFT70 v3.0

Used configuration: <https://github.com/frenck/Marlin/tree/frenck/config/frenck#frencks-marling-configuration>

My config is in sync with this repository (mainly adds buffers for advance OK and Octoprint).

**Comment by Sebazzz** [comment]
Looks like the fix for #87 also needs to be applied for G28. Upstream bug.
