### ISSUE TITLE
Z-offset != 30 during printing and runaway printer

### ISSUE THREAD

**Issue by unixluv** [CR6Community/Marlin#104]
### Description

While printing, I am unable to set z-offset to 0.30 from the CR-6 SE front panel. It will go to 0.29 or 0.31, but not 0.30.  During the attempt to do so, the front panel became unresponsive, so that it would not leave the z-axis setting screen even after repeatedly pressing the back button. I had to power off the printer and restart.

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. Print something that will take at least 10 mins to print.
2. Enter the front panel Tune menu.
3. set the z-offset to 0.30

**Expected behavior:** 

The expected behavior is to permit the 0.30 z-offset.

**Actual behavior:** 

The z-offset moves from 0.29 to 0.31

**Logging:**

I don't use a serial monitor or Octoprint with my CR-6SE due to known issues with the USB port.

### Additional Information

This is a fairly stock CR-6 SE. The filament feeder (extruder) has been replaced from stock with a Creality all metal one.  E-steps are set to 85.0 from a SD Card. 

Currently using firmware-20201106-192839.bin file.   https://github.com/CR6Community/Marlin

**Comment by Sebazzz** [comment]
This has been fixed in CF5 which will be released soon.
