### ISSUE TITLE
Temperature Setpoint Cycles between 120 and 0 during homing and leveling

### ISSUE THREAD

**Issue by ghost** [CR6Community/Marlin#108]
### Description
Temperature Setpoint Cycles between 120 and 0 during homing and leveling

### Steps to Reproduce

1. Enter Leveling menu.
2. Press Home. (bed is set to 50C, Hot end to 120C), system waits until temperature is stabilized. 
3. During Homing, temperature cycles between 120C and 0C.  Hot end temperature reduces to ~114-115C
4. Press Level.  Temperature of bed set to 50C, Hot End to 120C.  Nozzle moves to first position, setpoint goes to 0C, then 120C then 0C.  
5. At position 2, temperature set to 120C, no waiting, level proceeds, temp set to 0C, then 120C,  Actual temp settles around 114-115C.
6. repeats for all 16 positions.

**Expected behavior:** 

Temperature set to 120C, remains there until leveling completed.

**Actual behavior:** 

See steps above.

**Logging:**

Using only from printer UI. no log available.

### Additional Information

4.5.2 motherboard. beta 5 firmware.

https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-5-beta/CF5Beta-cr6-se-v4.5.2-mb-2020-12-30-14-19.zip

**Comment by Sebazzz** [comment]
This is not a bug but a feature. The hotend is turned off when probing.
