### ISSUE TITLE
Progress bar starts initially at 100% on the second print

### ISSUE THREAD

**Issue by Ranney1** [CR6Community/Marlin#112]
With the latest extui-dev release, the print progress bar is working correct.

When starting a second print (without turning the printer off between them) the progress bar will start at 100%.

Latest Marlin firmware for BTT mainboard and stock screen in use.

**Comment by Sebazzz** [comment]
Transferred from CR-6-touchscreen as its an interop glitch.

**Comment by Sebazzz** [comment]
I think there is not much we can do about this. We just show what Marlin thinks is the progress.

The progress is set from Octoprint via M73 - I suggest you add M73 P0 to your start gcode. Then the progress is reset before starting the print.
