### ISSUE TITLE
Sound Control setting not applied immediately after cold boot

### ISSUE THREAD

**Issue by Destructif** [CR6Community/Marlin#113]
### Description

If the touch screen beeping sound is switched off in the settings, once the printer is powered off and back on again the sound is active again, the touch screen shows that is is disabled.

Enabling and disabling it again will switch it off again but power cycling the printer will do the same thing again,

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. Disable Sound
2. Power Cycle Printer
3. Sound is back on even though the screen shows it as disabled - Need to re-enable and disable for it to turn off again.

**Expected behavior:** 

Sound to stay off when switched off and screen to match

**Actual behavior:** 

Screen shows sound disabled but still beeps

**Logging:**

N?A

### Additional Information

[What is your hardware configuration? Which mainboard? Custom mods like different hot-ends and extruders? BTT touch screen?] 4.5.2 Creality - Stock Unit

[If you compiled the firmware yourself - Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files]

[Provide pictures or links to videos that clearly demonstrate the issue.]

[Which *exact* firmware version did you flash? Provide a link to the download you have used.]

**Comment by Sebazzz** [comment]
Confirmed and already fixed in 83d8e7ebb34633692b4081441a8db9577df80c1a.

For now either:
- Go to PLA/PETG preheat settings and then click the back button.
- Use [gcode M501](https://marlinfw.org/docs/gcode/M501.html) (either through a file, or terminal, start gcode etc.) to make the settings in effect
