### ISSUE TITLE
Use consistent labels: print screen vs tuning screen

### ISSUE THREAD

**Issue by ztakis** [CR6Community/Marlin#115]
### Description

Print Screen shows feed rate not printing speed

**Expected behavior:** 

Print Screen shows feed rate instead of printing speed which is confusing as Tune Screen shows the expected printing speed adjustment. I think it would be better that Print Screen to display just FLOW  SPEED  FAN.

**Comment by Sebazzz** [comment]
This is about the inconsistency in the labels I guess? The underlying data is the same: Marlin has no concept of print speed - only feed rate.

**Comment by Thinkersbluff** [comment]
When we added control over Flow Rate, we also introduced the Feed Rate label, without going back & making other screens consistent with that term.  

As an Engineer, I find units of "%" make more sense for Rates than for Speeds.
Users with no prior experience of CNC or RepRap jargon are probably less comfortable with arcane terms like "Feed Rate", but it is certainly embedded in Marlin and in their LCD menus.  What terminology are you using for the BTT TFT Marlin mode menus?

To me, it makes a lot of sense to retain consistency with the legacy terms  Standardizing on RepRap vocabulary should facilitate a more rapid understanding of all 3D printing resources for newcomers.

**Comment by Sebazzz** [comment]
Yes - so update the Tune screen by replacing "Printing speed" with "Feed rate". 

@grobux I think you are quicker than me. Come to think of it, the bed temperature and nozzle temperatures use the same icon - is that intentional?

**Comment by BubuMVX** [comment]
No problem, I'll do it.

> The bed temperature and nozzle temperatures use the same icon - is that intentional?

A bit of laziness maybe. 😋 Also, in the icon lib used, the main differences around the "temperature" keyword is basically the height of the temp gauge. Anyway, I'll check that too.

**Comment by BubuMVX** [comment]
Fixed by https://github.com/CR6Community/CR-6-touchscreen/commit/d8d9133131b85af8eb88ae01f196fad8cd1f2bc2

I took the opportunity to make new custom icons for bed and nozzle temperatures. Very simple, based on the ones in the footer and a bit larger than other menu icons, but more clear I guess. I put them everywhere they were needed. I'm open to better ideas and suggestions.

![41_E_adjust](https://user-images.githubusercontent.com/2005901/107100965-212b7f00-6816-11eb-8466-a949aa96315a.png)

**Comment by jwrayburn** [comment]
Fantastic! Thanks!
Jerry

**Comment by ztakis** [comment]
May I suggest some icons for flow rate?

![image](https://user-images.githubusercontent.com/76840398/107110591-b9932500-6851-11eb-9d73-804ce54cb48c.png)

**Comment by Sebazzz** [comment]
Flow rate is extrusion rate, so I would suggest something that looks like an extruder. Marlin has already a similar icon for generic TFTs, [check here - second picture](https://damsteen.nl/blog/2020/11/06/flash-marlin-on-anet-et-printers#booting).

**Comment by Sebazzz** [comment]
@grobux Are these icons useful to you? I think the gray part is like a transparency key.

![flowrate](https://user-images.githubusercontent.com/1426097/107884736-eb158b80-6ef6-11eb-8d29-bdfed41244c4.png)
*Flow rate [extrusion multiplier]*

![feedrate](https://user-images.githubusercontent.com/1426097/107884824-4b0c3200-6ef7-11eb-806f-810f305a30fa.png)
*Feed rate [print speed]*

![hotend](https://user-images.githubusercontent.com/1426097/107884738-eb158b80-6ef6-11eb-8287-e930d4ef15a9.png)
*Hot-end*

![bed](https://user-images.githubusercontent.com/1426097/107884739-ebae2200-6ef6-11eb-9ec1-d5e29b078ed2.png)
*Bed*

![bed_heated](https://user-images.githubusercontent.com/1426097/107884740-ebae2200-6ef6-11eb-9219-24a571d9026b.png)
*Bed (heating)*

More icons can be found in the [Marlin/src/lcd/tft/bitmaps folder](https://github.com/CR6Community/Marlin/tree/extui/Marlin/src/lcd/tft/bitmaps).

So to complete this issue:

- Rename "print speed" to "feed rate" (done)
- Perhaps take a look at the icons but that is up to you @grobux 🙂

**Comment by Sebazzz** [comment]
@ztakis did some updates to the printing screen which I have committed to the repository. DWIN part is still to be done.

**Comment by Sebazzz** [comment]
![image](https://user-images.githubusercontent.com/1426097/109833196-596d8400-7c41-11eb-95fd-4ffd043b7960.png)

Current screen implemented by @ztakis with a bit of #208 mixed into it already.

For this item this has now been implemented and I'Il close this issue.

If anyone feels strong about feed rate vs print speed, flow rate vs extrusion multiplier, let's open a new issue for that.

Thanks again for @ztakis for implementing this.
