### ISSUE TITLE
Rapid Z Offset adjustment Cause Factory Reset

### ISSUE THREAD

**Issue by JFI611** [CR6Community/Marlin#123]
### Description

When rapidly adjusting the Z offset, the printer will factory reset and a M112 code will display on the touchscreen.

### Steps to Reproduce

1. Go to Z offset adjustment screen.
2. Rapidly adjust the Z offset. Either Up or Down. Doesn't Matter. This will also happen it adjusting durning a print.

**Expected behavior:** 

[What you expect to happen]

I expected the Z offset to adjust without issues.

[What actually happens]

Printer did a factory reset. 

**Logging:**

Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 11352)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 38001)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 32496)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 31811)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 14836)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 57071)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 65052)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 6476)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 58648)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 471)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 14091)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 59942)
Recv: //action:notification Settings Stored
Recv: Invoking handler for screen 52with VP=4164 value=3
Recv: start
Printer sent 'start' while already operational. External reset? Resetting line numbers to be on the safe side
Send: N0 M110 N0*125
Recv: PowerUp
Recv: Marlin CR6Comm-CR6-Rel5
Recv: 
Recv: echo: Last Updated: 2020-12-30 | Author: (Sebastiaan Dammann, CR-6 SE with stock motherboard)
Recv: echo:Compiled: Dec 30 2020
Recv: echo: Free Memory: 49079  PlannerBufferBytes: 1472
Recv: //action:notification CR-6 Community Ready.
Recv: echo:EEPROM version mismatch (EEPROM=ERR Marlin=V82)
Recv: SetNewScreen: 28
Recv: SetNewScreen (saving): 28
Recv: Mesh level index: 0
Recv: Mesh level index: 1
Recv: Mesh level index: 2
Recv: Mesh level index: 3
Recv: Mesh level index: 4
Recv: Mesh level index: 5
Recv: Mesh level index: 6
Recv: Mesh level index: 7
Recv: Mesh level index: 8
Recv: Mesh level index: 9
Recv: Mesh level index: 10
Recv: Mesh level index: 11
Recv: Mesh level index: 12
Recv: Mesh level index: 13
Recv: Mesh level index: 14
Recv: Mesh level index: 15
Recv: echo:Hardcoded Default Settings Loaded
Recv: Saving DWIN LCD setting from EEPROM
Recv: echo:Settings Stored (747 bytes; crc 30424)
Recv: //action:notification Settings Stored
Recv: echo:EEPROM Initialized
Recv: Taring probe
Recv: //action:prompt_end
Recv: BL24CXX Check succeeded!
Recv: echo:SD card ok
Recv: ok
Send: N0 M110 N0*125
Recv: ok
Send: M155 S2
Recv: ok
Send: M113 S2
Recv: ok

### Additional Information

[What is your hardware configuration? Which mainboard? Custom mods like different hot-ends and extruders? BTT touch screen?]

v4.5.2

CF5Beta-cr6-se-v4

**Comment by Sebazzz** [comment]
Confirmed. For now - don't go crazy on the Z-offset 😀

**Comment by Sebazzz** [comment]
This is fixed now :)

**Comment by JFI611** [comment]
Will this just be part of the next release?

**Comment by Sebazzz** [comment]
There is a prerelease in the #prerelease-testing channel in discord.
