### ISSUE TITLE
DGUSDisplayDef.cpp -- line 32 -- EStepsHandler.h ==> EstepsHandler.h (change first S to lowercase s) **only in root git source files

### ISSUE THREAD

**Issue by saxk** [CR6Community/Marlin#124]
// **Thank you** sharing your time and the knowledge you've worked so hard to attain is something that makes the world a better place. shine on...

// **Description**

compilation errored out with error message posted below. i.e.: looking for EStepsHandler.h but not able to locate as the actual filename is EstepsHandler.h

the call for EStepsHandler.h is in ./Marlin/src/lcd/extui/lib/dgus_creality/creality_touch/DGUSDisplayDef.cpp on line 32

as a workaround, I copied EstepsHandler.h to EStepsHandler.h in the same directory... compiled successfully.

// **EDIT** -- after digging in a bit more and downloading specific source, i noticed this is a non-issue. That is, the include filename issue only seems to be in the root git source files. i was able to compile without copying the file or editing the cpp file.

// **Steps to Reproduce**

1. clone code to fresh directory (git clone https://github.com/CR6Community/Marlin.git)
2. change directory from current to Marlin
3. compile (platformio run)
4. fail
5. try not to feel like your life has been a waste of everyone's time

// **Expected behavior:** 

// shiny new firmware.bin file to carry off and do with as i see fit

Building .pio/build/STM32F103RET6_creality/firmware-20210104-085725.bin
Checking size .pio/build/STM32F103RET6_creality/firmware-20210104-085725.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  20.8% (used 13640 bytes from 65536 bytes)
Flash: [===       ]  34.2% (used 179516 bytes from 524288 bytes)
======================================================= [SUCCESS] Took 9.34 seconds =======================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  SUCCESS   00:00:09.343
======================================================= 1 succeeded in 00:00:09.343 =======================================================

// :-)

// **Actual behavior:** 

fail to compile... easily worked around by creating include file or modifying code to reflect actual filename

Compiling .pio/build/STM32F103RET6_creality/src/src/libs/vector_3.cpp.o
Marlin/src/lcd/extui/lib/dgus_creality/creality_touch/DGUSDisplayDef.cpp:32:10: fatal error: ../creality_touch/EStepsHandler.h: No such file or directory
 #include "../creality_touch/EStepsHandler.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/STM32F103RET6_creality/src/src/module/endstops.cpp.o
*** [.pio/build/STM32F103RET6_creality/src/src/lcd/extui/lib/dgus_creality/creality_touch/DGUSDisplayDef.cpp.o] Error 1
======================================================= [FAILED] Took 32.52 seconds =======================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:32.521
================================================== 1 failed, 0 succeeded in 00:00:32.521 ==================================================

// :-|

// **Logging:**

see above

// **Additional Information**

compiling on Fedora23 (Linux xxxx.xxxxx.xxx 5.9.16-100.fc32.x86_64 #1 SMP Mon Dec 21 14:10:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

platformIO Core 5.0.4

git depot cloned on 20210104 @ ~01:30 PST

**Comment by Sebazzz** [comment]
I've fixed the include in 09d8b14 - thank you for reporting.
