### ISSUE TITLE
DGUS_LCD_UI_CREALITY_TOUCH is ambiguous

### ISSUE THREAD

**Issue by mrv96** [CR6Community/Marlin#139]
Hi, I open this issue in order to find a solution to avoid Marlin users confusion.

Looking this lines:
https://github.com/CR6Community/Marlin/blob/42916c7896608f91813d8896dc5f1a89a9de4ec8/Marlin/Configuration.h#L2250-L2262
it seems that this four options share the same hardware, but this is not the case.

The three original Marlin options works with T5UID1 display, while yours works with T5L display.

Do you think that is reasonable underline this aspect either using comments or changing the define?

IMHO add a reference to display hardware would be necessary also in official Marlin. Right now there are a lot of similar but different DGUS LCDs

**Comment by Sebazzz** [comment]
@grobux I think you found the original AliExpress link where to purchase this?

**Comment by BubuMVX** [comment]
I'm experimenting right now with a DWIN screen, reference DMG48270C043_03WTC (item+delivery is around 20€).
The last letter in the reference is for the type of panel : C=capacitive, R=resistive, and N=no touch.

I'm not 100% sure it's the same screen as the stock one, but the hardware is pretty much the same.
I flashed the Community screen firmware without too much trouble (had to do it from the SD card twice, maybe to correctly update the OS).

I didn't plugged it on my printer yet, I have to solder a connector, but it's promising.
