### ISSUE TITLE
Printing from host XYZ 

### ISSUE THREAD

**Issue by nicwilson58** [CR6Community/Marlin#140]
__Issues that do not follow this issue template will be closed__

### Description
during a print from host,  the "Printing from host" screen,  XYZ Axis values look wrong

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. print from host
2. look at XYZ axis values 
3. compare with postions of XYZ

**Expected behavior:** 

XYZ axis values to me meaningful 

**Actual behavior:** 

See attached screenshot.  Printing a model,   when at layer 227 @ 0.2 layer height,  Z was at 227*0.2 + 0.2 = 45.6,  Z Axis shows 4.56mm which is clearly wrong,  X & Y values also look meaningless given where model was on the bed.

**Logging:**

[Enter `M111 S247` in a serial monitor (Pronterface or Octoprint). Reproduce the issue, then copy the relevant logs here. 
For Octoprint you can either user serial.log or copy/paste the output from the terminal. More information: https://marlinfw.org/docs/gcode/M111.html ]

### Additional Information

[What is your hardware configuration? Which mainboard? Custom mods like different hot-ends and extruders? BTT touch screen?]
Std out of the box CRt
[If you compiled the firmware yourself - Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files]
N/A
[Provide pictures or links to videos that clearly demonstrate the issue.]
![137093987_1461282887408203_5177503408220947507_n](https://user-images.githubusercontent.com/58644781/104173247-3698cd80-5451-11eb-8fd8-e6f8f7bbf8a0.jpg)

[Which *exact* firmware version did you flash? Provide a link to the download you have used.]
Beta 5

**Comment by Sebazzz** [comment]
Duplicate with #111
