### ISSUE TITLE
[FR] Allow 180 degree rotation of the display

### ISSUE THREAD

**Issue by rancid-racer** [CR6Community/Marlin#141]
I would like to be able to rotate the image 180 on the initial orientation for my CR-6 so that the SD Card Slot is at the top of the board instead of the bottom.  This allows for an opportunity to reprint a back cover and make it easier for updates without removal of the panel.

**Comment by rancid-racer** [comment]
> I used a 15cm micro sd extender. It was a tight fit. I had to cut a notch in the back cover and pulled the display off of the bracket to insert the cable but it works well. I didn't have problems sticking the display back on but that could be an issue.

I purchased one as well and am currently measuring up the back cover to reprint with a notch already in place.  I just think that flipping the screen makes more sense but I'm working with what I am capable of.

**Comment by Sebazzz** [comment]
I agree! I'm going to build this because I'm too cheapskate to buy an SD adapter.

**Comment by ritchiedc** [comment]
Don't forget you'll still have to extend the control cable.On Jan 12, 2021 8:48 AM, Sebastiaan Dammann <notifications@github.com> wrote:
I agree! I'm going to build this because I'm too cheapskate to buy an SD adapter.

**Comment by Thinkersbluff** [comment]
I am enjoying my external SD card slot enormously.  
Being able to upload display firmware from the main board SD or USB would be even better.

**Comment by Sebazzz** [comment]
Yes, but there appear to be commands to do that, but I don't want to risk bricking the display. Besides, there is no way to show progress while the display is being flashed.

**Comment by Thinkersbluff** [comment]
> currently measuring up the back cover to reprint with a notch already in place.

This may help:
https://www.thingiverse.com/thing:4693106

**Comment by rancid-racer** [comment]
> > currently measuring up the back cover to reprint with a notch already in place.
> 
> This may help:
> https://www.thingiverse.com/thing:4693106

Thank you!  I got most of the measuring done but this will save me hours on Fusion360 and is exactly what I was working on.

**Comment by Sebazzz** [comment]
I think that a 180 degree turn is useful - but the problem is that display is completely misaligned. This also requires then a new display mount to be printed. For this reason, until such mount is available, I'm putting this on low priority.

**Comment by Sebazzz** [comment]
Closing this - feel free to reopen when a mount becomes available.
