### ISSUE TITLE
Bed level speed

### ISSUE THREAD

**Issue by GTIpunk87** [CR6Community/Marlin#142]
Hello, 
 I'm just wondering if it's possible to speed up the leveling process

**Comment by Sebazzz** [comment]
Yes, we could level at the original speed, but that would cause all the inaccuracy issues the previous and sometimes stock firmware also has.

**Comment by GTIpunk87** [comment]
Ah ok, i wasn't sure if this was the max speed-accuracy ratio. I'm sure you had looked into that. Thank you!

**Comment by krammerj2486** [comment]
I think bed leveling is Ok. I only do this once a while or when changing nozzle or so. The result is very good now and therefor speed low speed is no matter to me. I don't think repeating the leveling every print brings any advantage.

**Comment by Sebazzz** [comment]
@GTIpunk87 If you're able to compile the firmware, please feel free to do some accuracy tests and report back. Marlin devs upstream agree however that slower leveling generally means more accurate leveling. We've seen this also with this release of 5 beta - that this has resolved many leveling issues for many users.
