### ISSUE TITLE
Power loss recovery could start with  bed and nozzle heating prior to any movement

### ISSUE THREAD

**Issue by kds69** [CR6Community/Marlin#144]
Power loss recovery works great if filament can be detached from nozzle and 
 printed element still sticks enough to the bed.
Chances of succesful resuming print can be increased by helping to detach printed element from nozzle and making printed element glued to bed again.

A suggestion would be to offer to user to first recover operating temperature for the bed and nozzle prior to perform any movement of printer head.

Pre-heating the bed first, before printer head does homing. This would allow printed element to stick again to bed before any movement of the bed occurs.

Same for the nozzle, a pre-heating would allow smooth detachment of nozzle from item and avoid item to be taken away together with nozzle when printer head performs homing and ruins the chances to resume  (and risk to arm mechanism while going down during homing).

**Comment by Sebazzz** [comment]
Thank you for submitting your report.

I agree! This would normally be out of scope for this project. If we deviate too far from Marlin, merging becomes very hard and costs a lot of time in maintenance. We're all doing this in the evening off-hours 😉 

Luckily, this has recently been implemented in Marlin in commit 8edcf03715953d7752a3013662362c8a93f0288c via upstream issue [#20697](https://github.com/MarlinFirmware/Marlin/pull/20697) - so this will be included in next release of the community firmware.
