### ISSUE TITLE
[FR] Enable G20/G21 for Inch units.

### ISSUE THREAD

**Issue by CRCasey** [CR6Community/Marlin#149]
Request for G20/G21 inch unit support to be active in the default build.

I am attaching a laser diode module to my head, and I use LightBurn software on occasion.  The gcode it creates expects to have the G20/G21 since that program can use either unit.  I can manually edit the gcode, but if I have this issue so will others.

In configuration.h line 1593-1597 are:

`
//
// G20/G21 Inch mode support
//
//#define INCH_MODE_SUPPORT

`

They just need to be changed over to:

`
//
// G20/G21 Inch mode support
//
#define INCH_MODE_SUPPORT

`

It didn't seem to be worth a pull for this.
Thanks,
-Cecil

**Comment by Sebazzz** [comment]
Fixed in ec84751 - will be part of the next release.

Thank you for the suggestion.
