### ISSUE TITLE
Increase Z-Offset Resolution in the Level Screen  to 0.01 

### ISSUE THREAD

**Issue by ritchiedc** [CR6Community/Marlin#15]
### Description

Finer control over the Z-Offset is needed. Increasing the resolution from 0.05 to 0.01 would be helpful. I noticed that this has already been done in the screen firmware for the Print->Tuning screen.

#### Additional Information

File touch_lcd.cpp needs to be changed in 6 places between lines 978 and 995, reducing 0.05 to 0.01. See attached file
[touch_lcd.zip](https://github.com/CR6Community/Marlin/files/5362007/touch_lcd.zip)

Edit: There is a problem with float precision and a single press up or down does not always result in a displayed 0.01mm difference.  This can be compensated for by:

probe.offset.z = roundf(probe.offset.z*100.0 + 1.0)/100.0; // increment

and

probe.offset.z = roundf(probe.offset.z*100.0 - 1.0)/100.0; // decrement

**Comment by formless63** [comment]
Nice - this would definitely be an improvement.
