### ISSUE TITLE
When printing, indicated Z axis value is 1/10 of the real value

### ISSUE THREAD

**Issue by jurkstas** [CR6Community/Marlin#163]
__Issues that do not follow this issue template will be closed__

### Description

While printing Z is indicated, for example, as 0,02 mm instead of 0,2 mm (2 mm or so -> 0,2 mm)

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. Print something from Octopi.
2. Observe Z value on screen to be 1/10 of the true value.

**Expected behavior:** 
See true Z value.

**Actual behavior:** 
Seeing Z value divided by 10.

**Logging:**

[Enter `M111 S247` in a serial monitor (Pronterface or Octoprint). Reproduce the issue, then copy the relevant logs here. 
For Octoprint you can either user serial.log or copy/paste the output from the terminal. More information: https://marlinfw.org/docs/gcode/M111.html ]

### Additional Information
Model: CR-6 SE
Mainboard revision: 4.5.2
Firmware: [CF5Beta-ProbeHeaterOn-cr6-se-v4.5.2-mb-2020-12-30-14-24](https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-5-beta/CF5Beta-ProbeHeaterOn-cr6-se-v4.5.2-mb-2020-12-30-14-24.zip)
No intentional setting changes, no mods.
Printing from Octopi (printing from Host).

**Comment by Sebazzz** [comment]
Thank you for reporting. This has already been reported as #111 - please check that issue for details.
