### ISSUE TITLE
On screen keyboard in "Linear Adv Factor " doesn't show decimal point

### ISSUE THREAD

**Issue by j3ffrw** [CR6Community/Marlin#164]
### Description

On screen keyboard in "Linear Adv Factor " doesn't show decimal point when entering floating point number and seems to be limited to 3 digits(not that we wont be entering big K factor). 

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. Print any model
2. While printing , go to Tune menu
3. Adjust Linear Adv. Factor to say 1.1

**Expected behavior:** 

On screen keyboard should display "1.1"

**Actual behavior:** 

On screen keyboard shows "11."

### Additional Information

[What is your hardware configuration? Which mainboard? Custom mods like different hot-ends and extruders? BTT touch screen?]

BTT board on stock Cr6-se LCD 

[Provide pictures or links to videos that clearly demonstrate the issue.]

https://drive.google.com/file/d/1xlHkqK8vUa0NlmnjkV8D50EVR-aJzBrC/view?usp=sharing

[Which *exact* firmware version did you flash? Provide a link to the download you have used.]
https://github.com/CR6Community/Marlin/releases/tag/v2.0.7.3-cr6-community-release-6-pre2

**Comment by Sebazzz** [comment]
This has been fixed in [466166a13b7c3aa35a8e04aa6a16272064c6409e](https://github.com/CR6Community/CR-6-touchscreen/commit/466166a13b7c3aa35a8e04aa6a16272064c6409e).

[CR-6-touchscreen-2021-01-31.zip](https://github.com/CR6Community/Marlin/files/5899578/CR-6-touchscreen-2021-01-31.zip)
