### ISSUE TITLE
Homing while leveling causes dragging nozzle from center of the bed to the next leveling point

### ISSUE THREAD

**Issue by jurkstas** [CR6Community/Marlin#165]
__Issues that do not follow this issue template will be closed__

### Description

Homing while autoleveling causes dragging nozzle from the center of be bed to the next leveling point.

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. Start leveling, wait for 2nd leveling poing
2. Go back from Leveling status menu and press Home.
3. Observe the printer interrupt leveling with a homing procedure
4. When homing is done, nozzle is marked in the middle of the bed at Z=0
5. Leveling resumes by first moving horizontally to the next point while Z=0 and then proceeding with the vertical movement.

**Expected behavior:** 

Either cancel the leveling or first move up and the horizontally. Canceling would make more sense. As far as I can tell, there is no way to cancel leveling when it has begun.

**Actual behavior:** 

Described in repro steps. Leveling continues straight from homing.

**Logging:**

### Additional Information

Model: CR-6 SE
Mainboard revision: 4.5.2 
Firmware: [CF5Beta-ProbeHeaterOn-cr6-se-v4.5.2-mb-2020-12-30-14-24](https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-5-beta/CF5Beta-ProbeHeaterOn-cr6-se-v4.5.2-mb-2020-12-30-14-24.zip)
No intentional setting changes, no mods.

**Comment by Sebazzz** [comment]
Should be fixed for CF6 Pre3 - thanks for reporting.
