### ISSUE TITLE
The Move Y+ and Move Y- button labels are reversed vs X+, X-, Z+ and Z-

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/Marlin#173]
Pressing X+ or Z+ causes the displayed position to increase by the selected increment (e.g. 10mm).
Pressing X- or Z- causes the displayed position to decrease by the selected increment.

The "push" and "pull" labels on the Move Y buttons are intuitive, but:
Pressing Y+ causes the displayed position to _decrease_ by the selected increment.
Pressing Y- causes the displayed position to _increase_ by the selected increment.

Please consider reversing those two symbols, so that pushing the bed - which decreases the Y position - is labelled with a "-"
and "pullng" the bed - which increases the Y position - is labelled with a "+".

**Comment by BubuMVX** [comment]
Issue fixed by https://github.com/CR6Community/CR-6-touchscreen/commit/1a9eb4357aed6332064d17502a40b32365c106bb
