### ISSUE TITLE
[FR] Show Warning when Probed Mesh Min/Max range exceeds that which can be compensated for using ABL.

### ISSUE THREAD

**Issue by gleonard3** [CR6Community/Marlin#174]
It's not clear to me what that actual acceptable range is, but I have definitely experienced exceeding that limit, whereby some physical hardware tweaking of the printer itself is required.  If we worded a warning like this correctly, I think it would help a lot of new users.

Something like "WARNING:  Recommended Frame Squareness Check and Re-Level."

**Comment by Sebazzz** [comment]
There isn't really a limit. Marlin is about to compensate for 10mm in difference just fine. Try blocking the nozzle at one of the leveling points, then do a print. You will notice that the nozzle moves that amount up. 

It is this bed leveling probe which is just inaccurate - though I believe we fixed that mostly with CF5 beta (_not_ the ProbeHeatersOn download).

**Comment by gleonard3** [comment]
Great!  So this shouldn't concern me then?  https://i.redd.it/7q2aalmxepf61.png  I'm on a new Max with CF5.  When I got my SE over the Summer, this caused havoc for me.  Obviously Pre-CF.

**Comment by Sebazzz** [comment]
No, in my opinion not 🙂

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: George Leonard <notifications@github.com>
Verzonden: Friday, February 5, 2021 9:24:21 PM
Aan: CR6Community/Marlin <Marlin@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [CR6Community/Marlin] [FR] Show Warning when Probed Mesh Min/Max range exceeds that which can be compensated for using ABL. (#174)


Great! So this shouldn't concern me then? https://i.redd.it/7q2aalmxepf61.png<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fi.redd.it%2F7q2aalmxepf61.png&data=04%7C01%7C%7Ca9b2470c1651435d315808d8ca14062a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637481534633823554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lWAkkKlNOoAwLgXfl7WD1tZgvpl4Su81mAVlVFLsIOY%3D&reserved=0> I'm on a new Max with CF5. When I got my SE over the Summer, this caused havoc for me. Obviously Pre-CF.

**Comment by gleonard3** [comment]
Well in that case, I'm happy to adopt your opinion as my own.  Thanks!
