### ISSUE TITLE
Linear Advance Factor is multiplied by 10 upon entry

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/Marlin#175]
### Description
The Linear Advance Factor display appears to multiply the entered value by 10 upon entry and Marlin appears to use that amplified value.

### Steps to Reproduce

While printing, select Tune menu.
Select Linear Advance Factor
Enter 0.8 and hit ✅ 
Display shows 0.8 momentarily, then shows 8.00.
Sound from printer changes to lower pitch and slows down.
Select Linear Advance Factor again, enter 0 and hit ✅ 
Displayed value goes back to original speed and sound.
Select Linear Advance Factor and enter 0.08 and hit ✅ 
Displayed value is momentarily 0.08 then changes to 0.80.
Sound and speed of printer not noticeably changed.

**Expected behavior:** 

Expected display to show the value I entered and to use it.

**Actual behavior:** 

Printer sounds like it is using the displayed value but that value is an order of magnitude larger than entered.

**Logging:**

Tried to attach video. Got “Yowzah” response. Not sure how to shrink that.

### Additional Information

4.5.2 mb, stock display
Display and MB Firmwares both downloaded from their respective GitHub extui branches on 6 Feb 2021. Config files unchanged from downloaded versions.

**Comment by Sebazzz** [comment]
Done. Thanks for reporting.
