### ISSUE TITLE
Homing / bed leveling and nozzle temperature

### ISSUE THREAD

**Issue by Pla5ma** [CR6Community/Marlin#177]
### Description

During homing operations the heating of the nozzle switches off as soon as the nozzle goes down. But depending on the location of the nozzle this can lead to prolonged time and massive temperature drop. 

**Expected behavior:** 

Maybe the heating could be switched of at the second build plate tipping only to reduce the amount of time without heating. It would reduce time needed for homing and even bed leveling dramatically.

**Comment by Sebazzz** [comment]
Thank you for your suggestion. This has already been fixed upstream and will be incorporated in the CF6 release.
