### ISSUE TITLE
Z Height decimal incorrect. 

### ISSUE THREAD

**Issue by daveW11** [CR6Community/Marlin#182]
Z height in Version 5 release has decimal place as 0.68mm which is 6.8mm

All seems great apart from that so far. 

Thanks guys

**Comment by BubuMVX** [comment]
Hi @daveW11 and thanks for taking the time to report this issue.
We are aware of it and already fixed it (main reports: https://github.com/CR6Community/CR-6-touchscreen/issues/23 and https://github.com/CR6Community/Marlin/issues/111).
This patch will be available in Release 6, but if you're willing to compile the source code, you can have it right now.
Thanks again !

**Comment by Sebazzz** [comment]
Duplicate with #111
