### ISSUE TITLE
Ability to change thermistor tables for high temp hot ends.

### ISSUE THREAD

**Issue by craigrusso** [CR6Community/Marlin#185]
### Description

Would it be possible to be able to load new thermistor tables from the touch screen or switch between tables to support high temp hot ends like the mosquito?

**Comment by Sebazzz** [comment]
Are you referring to the functionality of [`M305`](https://marlinfw.org/docs/gcode/M305.html)? That would be possible, but then you're only half of the way there. You'd still need to recompile the firmware to allow those higher temperatures, and then at the point you might change the thermistor yourself from `Configuration.h`, agree?

**Comment by craigrusso** [comment]
Ah ok. I didn’t know if it where possible to make that functionality without having to recompile the firmware. Thank you though.
