### ISSUE TITLE
Strange home screen after flashing CR-6 Beta 5 to 4.5.3 Mobo

### ISSUE THREAD

**Issue by openscript** [CR6Community/Marlin#188]
### Description

I've followed Toms instruction video and also think I've read all the instructions before upgrading to the Happy New Year Edition.
Hopefully this is not a duplicate and if so, I'm sorry. I have googled for quite a while. First of all, everything seems to work, I even could level and print successfully, but the home screen looks rather strange:

![image](https://user-images.githubusercontent.com/1105080/108204156-bc302d00-7123-11eb-8b33-4770ec34ceb1.png)

If I click the buttons where they are supposed to be, navigating is no problem. The other screens look fine:

![image](https://user-images.githubusercontent.com/1105080/108204286-e550bd80-7123-11eb-96f5-a43a37b79e76.png)

### Steps to Reproduce

0. I've downloaded the `CF5Beta-cr6-se-v4.5.3-mb-2020-12-30-14-19.zip` to my computer.
1. I've formatted a 8GB Intenso card with FAT32 4096.
2. Copied the bin file on the card and nothing else was on it.
3. Inserted it into the printer and started.
4. The loading bar took longer than usual, but it started. The place where the version was displayed stayed empty.
5. I've shutdown the printer.
6. Formatted the card again the same way and copied the whole DWIN folder onto it.
7. I removed the display and the cover. Inserted the card. Made sure it doesn't touch the case or anything conductive.
8. It took a moment or two but seemed to be successful. I've compared the output with the screenshots.
9. Then I started again, it booted and the issue appeared.

**Expected behavior:** 
No distorted home screen.

**Actual behavior:** 
Home screen is distorted.

**Logging:**
None

### Additional Information

![image](https://user-images.githubusercontent.com/1105080/108205030-d4547c00-7124-11eb-89b2-348dca3a7d24.png)

![image](https://user-images.githubusercontent.com/1105080/108205069-dfa7a780-7124-11eb-83ee-9404bb31cd35.png)

**Comment by Sebazzz** [comment]
Wow, that's pretty odd. Make sure you've started with a clean SD card when flashing the touch screen. This result is typically seen when older files reside on the SD card.

**Comment by openscript** [comment]
I don't know what should be the resolution of this. It's just strange.

![image](https://user-images.githubusercontent.com/1105080/108253068-a76e8c00-7159-11eb-9edb-844b8d76bdac.png)

The SanDisk card always makes the screen faulty. Glitches or it suddenly freezes. I really wish to know why this happens, but this mystery is probably hard to uncover..

Thanks everybody for trying to help me out and also for creating the community edition :)

**Comment by Sebazzz** [comment]
Thank you for your update. I will update the flashing instructions.
