### ISSUE TITLE
[FR] Allow more tuning of axis settings

### ISSUE THREAD

**Issue by Sebazzz** [CR6Community/Marlin#189]
Users should be allowed to adapt their axis settings.

First mock-ups:
![image](https://user-images.githubusercontent.com/1426097/108263850-0edf0880-7167-11eb-8259-7f851ac8ee82.png)

![image](https://user-images.githubusercontent.com/1426097/108263860-11416280-7167-11eb-9e98-45689d0e54aa.png)

**Comment by Sebazzz** [comment]
Ready for further graphics fine tuning.

**Comment by JamesSF69** [comment]
*whispers, change the red bar color!  LOL I still think it's an error when I glance over  LOL

**Comment by Sebazzz** [comment]
**Movement screen**
![image](https://user-images.githubusercontent.com/1426097/108555788-3e704b00-72f6-11eb-856a-4eac2eeb7c9c.png)

Each axis goes to the axis screen. The axis screen dynamically changes title

**Axis screen**
![image](https://user-images.githubusercontent.com/1426097/108555798-416b3b80-72f6-11eb-8842-f482fa4d6615.png)

The following button is only available on BTT boards and black/hidden otherwise:
![10_AxisSettingsAvailable](https://user-images.githubusercontent.com/1426097/108556477-585e5d80-72f7-11eb-9ecd-1dd175b50fcd.png)

**TMC settings**
![image](https://user-images.githubusercontent.com/1426097/108556706-bb4ff480-72f7-11eb-92b1-24f817f2f8d6.png)

**Advanced settings**
![image](https://user-images.githubusercontent.com/1426097/108556532-71ffa500-72f7-11eb-9f21-76182f563f5f.png)

**Icons**
This is the base line now.

@grobux If you're having a go at these screens I've tried to use icons from fontawesome which you use iirc:

- Steps/mm and travel: https://fontawesome.com/icons/arrows-alt-h?style=solid
- X/Y icons: similar to that arrow
- Z: Z-offset icon
- Advanced settings and hybrid threshold: https://fontawesome.com/icons/wrench?style=solid
- Stepper current: https://fontawesome.com/icons/bolt?style=solid
- Stealthchop: https://fontawesome.com/icons/volume-up?style=solid
- Acceleration: https://fontawesome.com/icons/external-link-square-alt?style=solid
- Feedrate: existing icon
- Jerk: I drew it myself. Jerk is sudden change of speed instead of using acceleration, so I figured to draw a line graph.
- TMC settings: https://fontawesome.com/icons/microchip?style=solid
- Retract acceleration: I used the extruder icon of #115 and reversed it

No comic sans 😁

**Comment by BubuMVX** [comment]
Thanks, I'm on it !

**Comment by Sebazzz** [comment]
@grobux One thing I forgot is that I added the button to access this screen next to the info button. But that is just because it is the only logical place to put it and there isn't any space elsewhere😉

**Comment by Sebazzz** [comment]
@ztakis Good work on this pull request! https://github.com/CR6Community/CR-6-touchscreen/pull/41

I found a few small typo's, other than that, everything looks cool.

**Comment by Sebazzz** [comment]
With this PR this is pretty much complete: https://github.com/CR6Community/CR-6-touchscreen/pull/42

There is the TMC settings button, might be a minor thing.
