### ISSUE TITLE
Can anyone help with cr6se screen on ender 3pro 4.2.2 board 

### ISSUE THREAD

**Issue by 3dprinte** [CR6Community/Marlin#190]
![13F37B5C-4E4D-4C1E-B9A0-12D64D074CBF](https://user-images.githubusercontent.com/79272106/108387933-1a204b80-71dc-11eb-82bc-986c17e05be4.jpeg)
![13729910-9E85-48D0-BAE6-A932685C20FA](https://user-images.githubusercontent.com/79272106/108387943-1d1b3c00-71dc-11eb-81fa-924bcfd9d9b0.jpeg)
 
 so I know there has to be a way to get this to work I’m just not really good with vs code supposed to be ply and play no firmware from creality works on it checked and checked no link I bought this on Amazon it was listed as plug and play for ender 3 ender 3 pro how ever no link for firmware 😞😞😞😞

**Comment by Sebazzz** [comment]
Sorry, the CR-6 firmware is not purposely compatible with the Ender 3. I suggest you contact your seller for the correct firmware.

**Comment by 3dprinte** [comment]
this can can be done speaking to smith3d now don't need that negativity bro u can stay simple i wil always find a way to improve things
