### ISSUE TITLE
ender 3 pro cr6se touchscreen display 

### ISSUE THREAD

**Issue by 3dprinte** [CR6Community/Marlin#192]
[Ender-3Pro V4.2.2.zip](https://github.com/CR6Community/Marlin/files/6006277/Ender-3Pro.V4.2.2.zip)

[jay.zip](https://github.com/CR6Community/Marlin/files/6006274/jay.zip)

isn't working properly can anyone help compile?
![149605546_445224929949685_2809052774148177399_n](https://user-images.githubusercontent.com/79272106/108430183-fa564b00-720e-11eb-960b-2fc9812611e9.png)

**Comment by Sebazzz** [comment]
You need to contact your seller or the party where you got those firmware files for, I'm sorry. You may also be able to ask around the various Ender 3 communities.

This particular Github is for the CR-6 Community Firmware. While this firmware _might_ be able to run on other non-CR6 hardware and I'm happy to help with that, I can't help with compiling _different_ firmware for _different_ hardware. That is out of scope.

If I'm incorrect please restate your question.
