### ISSUE TITLE
Visual indicator that Stepper Motors are enabled/disabled

### ISSUE THREAD

**Issue by luds66** [CR6Community/Marlin#194]
### Description

Enhancement Request:

Just started using release 5 and noticed that unlike the stock firmware there is no visual indicator that stepper motors are enabled/disabled in the Prepare menu. I thought this would be nice to have, possibly like for the LED or Standby options.

**Comment by Sebazzz** [comment]
Thank you for your report.

There isn't really a way to ask Marlin that the stepper motors are disabled. As you may have noticed, on the stock firmware (1.0.2 and 1.0.3.7 at least) the "off" button never shows. It is all fake. 

The only thing we have is that axis might not be "trusted", and we show this in the movement menu as red numbers.
