### ISSUE TITLE
[FR] After ABL has completed, stay on mesh display screen until Back is selected

### ISSUE THREAD

**Issue by ztakis** [CR6Community/Marlin#195]
### Description

After ABL has completed, stay on mesh display screen until Back is selected.
Also as a confirmation that ABL has run and completed successfully.

**Comment by JamesSF69** [comment]
> ### Description
> After ABL has completed, stay on mesh display screen until Back is selected.
> Also as a confirmation that ABL has run and completed successfully.

Yep, I think this might be nice. We do have a "view mesh", but maybe just a delay instead of an immediate change of screen at the last probe.

**Comment by Sebazzz** [comment]
Agree, now we have the view mesh screen this screen has actually some value so we might as well remain on the screen.

Will still return immediately after the last point when leveling from a print though.

**Comment by ztakis** [comment]
If you agree then can you please also disable steppers after ABL completes? Thank you :)
