### ISSUE TITLE
Validation Pattern does not cancel (R6PRE4)

### ISSUE THREAD

**Issue by lektriq** [CR6Community/Marlin#207]
### Description

Pressing _Cancel_ during use of _Validation Pattern_ does not fully cancel print, circle outlines continue to print.

### Steps to Reproduce

1. Press _Run validation pattern_
2. Allow the pattern to start printing
3. Press _Cancel_

**Expected behavior:** 

Printer stops task and moves to home position.

**Actual behavior:** 

On pressing cancel the printer continues to print circle outlines, offset from their positions, with the printer attempting to move off the front of the bed.*

_*Note, secondary issue with travel noise, will make another issue._

**Logging:**

### Additional Information

Motherboard @ 4.5.2

Firmware @ https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-6-pre4/CF6-Pre4-cr6-se-v4.5.2-mb-2021-02-28-13-49.zip

![Mesh-validation-print-cancel-issue](https://user-images.githubusercontent.com/7228750/109677965-15f81480-7b72-11eb-9a5b-47d772845033.jpg)

https://user-images.githubusercontent.com/7228750/109679000-1644df80-7b73-11eb-9df5-b8fe054028b7.mp4

**Comment by Sebazzz** [comment]
Thank you. This has now been fixed.
