### ISSUE TITLE
[FR] Home without preheating

### ISSUE THREAD

**Issue by lukemaurer** [CR6Community/Marlin#215]
__Issues that do not follow this issue template will be closed__

### Description

If I'm doing moves using the menu, I don't usually need them to be 100% precise—it's usually because I'm checking my camera setup. It's then obnoxious to have to wait for it to heat the bed when I tap Home. I'd suggest a pop-up dialog *offering* to preheat if the user taps Home on a cold printer.

### Steps to Reproduce

*If this is a Bug Report, please describe the steps needed to reproduce the issue*

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expect to happen]

**Actual behavior:** 

[What actually happens]

**Logging:**

[Enter `M111 S247` in a serial monitor (Pronterface or Octoprint). Reproduce the issue, then copy the relevant logs here. 
For Octoprint you can either user serial.log or copy/paste the output from the terminal. More information: https://marlinfw.org/docs/gcode/M111.html ]

### Additional Information

[What is your hardware configuration? Which mainboard? Custom mods like different hot-ends and extruders? BTT touch screen?]

[If you compiled the firmware yourself - Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files]

[Provide pictures or links to videos that clearly demonstrate the issue.]

[Which *exact* firmware version did you flash? Provide a link to the download you have used.]

**Comment by Sebazzz** [comment]
Thank you for your suggestion.

You may not be aware that in the upcoming Community Firmware release 6 there are settings to customize heating, including not heating at all (set temperatures to zero or ambient). Would that work in your case?

Otherwise I might consider not preheating for homing at all, or at least not waiting for the temperatures from the movement menu. I agree that in the movement menu there should be less need to preheat.

**Comment by Thinkersbluff** [comment]
> Otherwise I might consider not preheating for homing at all, or at least not waiting for the temperatures from the movement menu. I agree that in the movement menu there should be less need to preheat.

This sounds like a very good idea.
As long as prints always include a G28 in their start gcode, the ABL & Z-offset should know where the bed is.

**Comment by ssendev** [comment]
When using the printer as a plotter this is also important but in release 6 preview 5 setting heating to zero solves it.
But it would be nice to have a gcode command to change the settings otherwise i always have to go to the printer.

**Comment by Sebazzz** [comment]
There is! Check the output of M503 and look for the line that says C001. Good luck!

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: ssendev ***@***.***>
Verzonden: Wednesday, March 17, 2021 4:10:12 PM
Aan: CR6Community/Marlin ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [CR6Community/Marlin] [FR] Home without preheating (#215)


When using the printer as a plotter this is also important but in release 6 preview 5 setting heating to zero solves it.
But it would be nice to have a gcode command to change the settings otherwise i always have to go to the printer.

**Comment by lukemaurer** [comment]
> Thank you for your suggestion.
> 
> You may not be aware that in the upcoming Community Firmware release 6 there are settings to customize heating, including not heating at all (set temperatures to zero or ambient). Would that work in your case?
> 
> Otherwise I might consider not preheating for homing at all, or at least not waiting for the temperatures from the movement menu. I agree that in the movement menu there should be less need to preheat.

Possibly, though I'm always weary of changing a setting that I'll forget to change back. And if I just need to nudge the X-carriage over to fix something, that's a lot of taps if I want to turn heat-on-movement off, do the movement, then turn it back on.

**Comment by Thinkersbluff** [comment]
> > Thank you for your suggestion.
> > You may not be aware that in the upcoming Community Firmware release 6 there are settings to customize heating, including not heating at all (set temperatures to zero or ambient). Would that work in your case?
> > Otherwise I might consider not preheating for homing at all, or at least not waiting for the temperatures from the movement menu. I agree that in the movement menu there should be less need to preheat.
> 
> Possibly, though I'm always weary of changing a setting that I'll forget to change back. And if I just need to nudge the X-carriage over to fix something, that's a lot of taps if I want to turn heat-on-movement off, do the movement, then turn it back on.

Would it help if there were separate Home X and Home Y buttons as options on the Move screen? Would they need to raise Z a few mm to avoid striking anything but not require pre heating before moving?  

What if disable steppers was available on that screen?  Is it homing you need or just to push the head or bed out of the way? 

Have you tried just tapping the axis position field, to enter a new position for the axis? (No new buttons required, if that works for you)

**Comment by Sebazzz** [comment]
This has now been implemented, but only from the movement screen using a trick. I didn't build an extra gcode parameter.
