### ISSUE TITLE
"Print from host" notification does not overwrite previous SD Card print filename if that name is longer than 18 characters

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/Marlin#216]
Using CF6 Pre 5.
Print from SD card a file whose name is 19 or more characters long.

e.g.:
![PrintFromSDBanner_CF6Pre5](https://user-images.githubusercontent.com/36551518/110811658-dd80c680-8254-11eb-8395-5a748a736cc0.jpg)

Stop Print.
Print any file from the Host.

Printer will show: "Printing from hostab" where "ab" are the 19th and 20th character in the previous SD card print filename.

e.g: 
![PrintFromHostIOBannerBug_CF6Pre5](https://user-images.githubusercontent.com/36551518/110811929-289ad980-8255-11eb-8b56-b9fa328e6bfc.jpg)

When printing from host, this screen should always show:
![PrintFromHostBanner_CF6Pre5](https://user-images.githubusercontent.com/36551518/110812034-4405e480-8255-11eb-8967-be12963d1406.jpg)

**Comment by Sebazzz** [comment]
Thanks. Fixed!
