### ISSUE TITLE
E-Steps temperature setting not being applied

### ISSUE THREAD

**Issue by ilgrank** [CR6Community/Marlin#218]
### Description

While doing e-steps calibration, I've accepted the default of 210°C / 100mm and everything was ok.
Since I was trying to find out if my extruding was skipping at lower temps, I decided to give it another try at 180°C
I set the temp to 180 and tried again. The hotend temp stayed at 210°C all the time, even if the display was still reporting my set temperature of 180°C

### Steps to Reproduce

1. Do an e-steps calibration at 210°C
2. After that, do another calibration at 180°C
3. The temperature remains at 210°C.

**Expected behavior:** 
Hot-End temperature should go to the set temperature.

**Actual behavior:** 
Temperature remains at the default of 210°C
**Logging:**
couldn't capture logs,I'll try tomorrow.

### Additional Information
Stock CR-6, Community FW4 (I've seen CFW5 does not add any fix about this)
4.5.2 motherboard

[Provide pictures or links to videos that clearly demonstrate the issue.]
Same as with the logs, I've reproduced this twice but I did not get pics at the time, I'll try tomorrow.

[Which *exact* firmware version did you flash? Provide a link to the download you have used.]
https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-6-pre4/CF6-Pre4-cr6-se-v4.5.2-mb-2021-02-28-13-49.zip

**Comment by Thinkersbluff** [comment]
Hi.  You are performing esteps calibration, but using a function designed only for lading and unloading filament. By CF 6, we had that figured out and built in an esteps calibration tool.  The CF 4 alpha version will not work for you.

**Comment by Sebazzz** [comment]
Are you setting the temperature lower whrn you've already pressed on the "run extrusion" button?

**Comment by ilgrank** [comment]
No, I'm setting the temperature first and then "run extrusion"

**Comment by Thinkersbluff** [comment]
I can confirm that on my BTT mb with stock TFT, running the 11 March Nightly firmware, if the set temperature is below the current nozzle temperature when Run Extrusion is pressed, the esteps function does not wait for the nozzle to cool and the displayed nozzle target and actual temperatures do remain at their previous (higher than set point temperature) while the esteps extrusion completes.

If the set temperature is higher than the actual temperature, esteps does heat first.


![BD9C2DF7-D259-4930-B564-3524D129AAEA](https://user-images.githubusercontent.com/36551518/111088972-23ad8280-8500-11eb-972f-20737f87f4ee.jpeg)
![8ECC3F27-40C2-4C30-BDF7-22E877996F93](https://user-images.githubusercontent.com/36551518/111088999-3c1d9d00-8500-11eb-9220-4f59d3513389.jpeg)

**Comment by Sebazzz** [comment]
Ah right, yes, I never thought of it that one might want to _cool down_ as well.
