### ISSUE TITLE
Screen timeout function not functioning as intended

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/Marlin#227]
### Description

The screen timeout function is not working as expected:

1. A timeout value of 656 seconds or more implements an actual timeout of t-655 seconds. 
2. The initial timeout value is set to 60 seconds, but the actual timeout value implemented is still 30 seconds unless and until the user accesses and then leaves the timeout setting screen.
3. Unlike screen brightness, if a new screen timeout value is entered, it does not take effect until the user exits that screen.

### Steps to Reproduce

1.1.  Access the screen timeout screen.
1.2. Enter a value of 656.
1.3. Press Back.
1.4 Screen now times out after 1 second.
1.5 Repeat 1.1 thru 1.3, but enter 660 at 1.2
1.6 Screen now times out every 5 seconds...

2.1 Power up the printer.
2.2 Screen dims after 30 seconds
2.3 Access the screen timeout screen
2.4 Note that the timeout parameter is set to 60 seconds
2.4 Exit the screen timeout screen
2.5 Screen now times out after 60 seconds

3.1 Access the timeout screen
3.2 Enter 10 seconds
3.3 Wait for screen to timeout
3.4 Notice that screen does not time out 10 seconds later
3.5 Exit the screen with Back
3.6 Notice the screen does time out 10 seconds later

**Expected behavior:** 

1.4 screen should timeout after 656 seconds
AND 1.6 screen should timeout after 660 seconds 
2.3 screen should timeout after 60 seconds 
OR 2.4 default value should be set to 30 seconds
3.4 screen timeout should take effect when entered, not after selecting Back.

### Additional Information
Using BTT SKR CR6 with stock TFT.
Using Release 6 Pre 6

**Comment by Sebazzz** [comment]
The maximum allowed timeout setting is 655 so I limited it, but it appears the that screen timeout is only taking effect after the next touch, so not much I can do about that.
