### ISSUE TITLE
[FR] Arc Support

### ISSUE THREAD

**Issue by Schallabajzr** [CR6Community/Marlin#23]
### Description

I would like to use https://github.com/FormerLurker/ArcWelderPlugin, but it requires ARC support. Is that something that can be implemented?

### Feature Workflow
Ability to process G2 and G3 commands.

```
Send: G2
Recv: echo:Unknown command: "G2"
```

**Comment by Schallabajzr** [comment]
Tried it. Seems to be working without issue out of the box.

**Comment by Sebazzz** [comment]
Still keeping this open though - we still need to implement this in the default config we ship :)

**Comment by Sebazzz** [comment]
@Nushio or @nickacker you already committed something for this, no?

**Comment by Nushio** [comment]
I basically turned the feature on. I've tested this a bit (about 8 different prints, from sdcard and octoprint) and so far, nothing's caught fire.

**Comment by Sebazzz** [comment]
My question was whether you committed it 😁

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Juan Rodriguez <notifications@github.com>
Verzonden: Wednesday, October 28, 2020 10:24:26 PM
Aan: CR6Community/Marlin <Marlin@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [CR6Community/Marlin] [FR] Arc Support (#23)


I basically turned the feature on. I've tested this a bit (about 8 different prints, from sdcard and octoprint) and so far, nothing's caught fire.

**Comment by Sebazzz** [comment]
Fixed on main branch and extui branch.

**Comment by Sebazzz** [comment]
Ready for next release.
