### ISSUE TITLE
Mesh validation not working

### ISSUE THREAD

**Issue by jsturm** [CR6Community/Marlin#230]
I have a Kickstarter CR-6 SE with MoBo 4.5.2. and CF 6 pre 6.
If I try to do a testprint (Mesh validation) from the LCD I can wait for ages - nothing happens. Only I can see, the themperatures are OK and a yellow text says: Starting...
I reflashed the FW 2 times - no success
![DSC01401 (2)](https://user-images.githubusercontent.com/1495817/112017562-0430de00-8b2e-11eb-8975-bd6eb24f93f0.JPG)

**Comment by Sebazzz** [comment]
Can you collect a serial log please, and also try a different bed temperature.

**Comment by jsturm** [comment]
I use a BuildTack surface wich sticks perfect at 35° - but setting the bedtemp. to 50° works perfect. THX
