### ISSUE TITLE
[FR] Extruder stepper direction change on LCD

### ISSUE THREAD

**Issue by esunayg** [CR6Community/Marlin#246]
It would be pretty useful.

**Comment by Sebazzz** [comment]
This is a Marlin limitation, to not have this configurable. While this would indeed be useful, base Marlin must provide support first. I try to stay clear of stepper motor control, so I suggest you ask it upstream instead.

Until then, recompile firmware or switch the physical wires.

**Comment by esunayg** [comment]
Thanks for explaining.
