### ISSUE TITLE
[FR] Allow editing the leveling mesh while printing

### ISSUE THREAD

**Issue by Sebazzz** [CR6Community/Marlin#256]
### Is your feature request related to a problem? Please describe.

Some users are, after multiple attempts, not able to get leveling right. This is caused by hardware issues which these users cannot resolve (due to the hardware or required skill level).

### Are you looking for hardware support?

N/A

### Describe the feature you want

It would be useful for these users to be able to access and modify the leveling mesh while printing their first layer. This builts on top of manual bed leveling built in #209.

**Comment by Sebazzz** [comment]
(It might be able to extend this also the mesh leveling test pattern - so it can be changed while it is being printed - but I wouldn't know where to place that button @ztakis)

**Comment by Sebazzz** [comment]
I've implemented a button @ztakis - Would you have time to update the PSDs? 
Note: the label on the "extra tuning" screen should actually read "Edit" instead of "View".

**Comment by ritchiedc** [comment]
I was thinking about something similar the other day as I was trying to fine tune my mesh with a feeler gauge. I was constantly having to go between the view mesh screen to adjust values and the movement screen to go to difference spots. A manual assist function as part of the view mesh screen may help with this. It might work something like this: when you select a mesh location the nozzle moves to that location and then you can adjust the height similar to the z offset and when it's good per the feeler gauge you save that value. I guess you'd want to set the feeler gauge height at the home position to start with.

**Comment by Sebazzz** [comment]
That is something else entirely that warrants its own feature request.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Ritchie Christian ***@***.***>
Verzonden: Sunday, May 2, 2021 11:50:00 PM
Aan: CR6Community/Marlin ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Author ***@***.***>
Onderwerp: Re: [CR6Community/Marlin] [FR] Allow editing the leveling mesh while printing (#256)


I was thinking about something similar the other day as I was trying to fine tune my mesh with a feeler gauge. I was constantly having to go between the view mesh screen to adjust values and the movement screen to go to difference spots. A manual assist function as part of the view mesh screen may help with this. It might work something like this: when you select a mesh location the nozzle moves to that location and then you can adjust the height similar to the z offset and when it's good per the feeler gauge you save that value. I guess you'd want to set the feeler gauge height at the home position to start with.

**Comment by ztakis** [comment]
> 
> 
> I've implemented a button @ztakis - Would you have time to update the PSDs?
> Note: the label on the "extra tuning" screen should actually read "Edit" instead of "View".

Are you OK  with this:

**Comment by ztakis** [comment]
![23_Screens](https://user-images.githubusercontent.com/76840398/116870031-70692c00-ac1a-11eb-83e0-c9b015fe4467.png)

**Comment by Sebazzz** [comment]
Looks good!

**Comment by ztakis** [comment]
While attempting to use this feature, got stuck in the leveling screen. Back button doesn't work and the scroller says:
"Wait for leveling completion..."

**Comment by Sebazzz** [comment]
This has been fixed.
