### ISSUE TITLE
Move menu z height buttons behave erroneously

### ISSUE THREAD

**Issue by ztakis** [CR6Community/Marlin#257]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

While in the 'Move' menu, Z+ and - buttons behave erroneously:
If increment is set to 10mm, Z+ moves up 10mm, 110mm, 250mm.
If increment is set to 1mm, Z+ moves up 1mm, 11mm, 111mm, 250mm.
If increment is set to 0.1mm, Z+ moves up 0.10mm, 1.10mm, 11.10mm, 111.10mm, 250mm.

I think it is related to issue 'Z coordinate should display two decimal places' #255

### Version of CR6Community Firmware

Rel6.1-PreX

### Printer model

Creality CR-6 SE

### Motherboard

Creality v4.5.2

### Display

Creality CR-6 stock touch screen

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by Sebazzz** [comment]
Confirmed. It wasn't as straightforward 😐
