### ISSUE TITLE
[FR] Firmware retraction settings are not saving into eeprom

### ISSUE THREAD

**Issue by esunayg** [CR6Community/Marlin#258]
CF6.1pr3
I am using retract override feature, and changing the settings while printing. They are working on current print but not saved on eeprom. Neither retract override on/off switch nor the settings I made inside of it. I thing they should be stored. I dont know it is how it was intended btw.

**Comment by Sebazzz** [comment]
This is intentional, because retraction settings differ per print. I recommend to let your slicer put in the correct values via the start gcode: https://damsteen.nl/blog/2021/05/06/adjustable-retractions-during-printing-with-marlin-firmware-retractions
