### ISSUE TITLE
[FR] Manual control of extruder

### ISSUE THREAD

**Issue by astralaster** [CR6Community/Marlin#261]
### Is your feature request related to a problem? Please describe.

There are options for every stepper motor in the printer to run manually, but I cannot use the extruder without heating the nozzle (filament load / unload feature).

### Describe the feature you want

Add motor controls for the extruder in the prepare menu.

**Comment by JamesRayn** [comment]
As a workaround maybe M302 (Cold Extrude) can help you.

https://marlinfw.org/docs/gcode/M302.html

**Comment by Sebazzz** [comment]
Yes, manual extrusion support is only supported with an hot hot-end. On stock Marlin you also need to drop down to serial commands.
