### ISSUE TITLE
Smart Filament Sensor Support for Stock 4.5.2 Board

### ISSUE THREAD

**Issue by S7EN** [CR6Community/Marlin#268]
Is it possible to easily replace the stock filament runout sensor and attach a Bigtreetech Smart Filament Sensor on the 4.5.2 Board instead and run it with the Community Firmware?

**Comment by TommyC81** [comment]
Also interested in this. Does the BTT smart sensor work as a slot-in replacement for the stock filament sensor?

**Comment by jjhu** [comment]
It does seem to have the same connection. What's the added value to this sensor though? I see that it detects when the filament is broken in the sensor, the print will stop. That's also the same feature the current runout sensor has.

**Comment by S7EN** [comment]
It also detects if filament is moving. When the nozzle is clogged this is very helpful.

**Comment by jjhu** [comment]
Ah interesting feature, the CFW should be able to accept the BTT smart sensor hardware wise (since it's the same connected). Software wise only a few modifications in the configuration files should do the trick, https://www.youtube.com/watch?v=9gLSJIxiuwo start at 3:05.

**Comment by Sebazzz** [comment]
It is supported in the sense that the underlying Marlin supports it, but it cannot be enabled dynamically. You need to compile the firmware yourself. I have written an article on this earlier: https://damsteen.nl/blog/2021/01/08/how-to-compile-cr6community-marlin-with-vscode-platformio

Good luck!
