### ISSUE TITLE
[FR] Sleep mode after print

### ISSUE THREAD

**Issue by DuckAvenger** [CR6Community/Marlin#271]
### Describe the feature you want

Please add a sleep mode function, where the extruder fans stops x-minutes after the print is completed.

Thanks in advance

**Comment by scratchfury** [comment]
The extruder fan cannot be controlled. It has constant power and will always be on.

**Comment by Sebazzz** [comment]
This is correct. If you ever have a printer where it can be controlled - it is a fixed setting in Configuration_adv.h.
