### ISSUE TITLE
[BUG] (enter short bug summary here)

### ISSUE THREAD

**Issue by flav05** [CR6Community/Marlin#273]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

hello , 
je rencontre un souci j'etait sous le cr 6community depuis 7-8 mois tout impeccable et hier plantage du firmware impossible de lancer du coup ce matin réinstallation de la machine impeccable et quand j'ai voulut lancer un callibrage j'ai eu un souci 
![IMG_0593](https://user-images.githubusercontent.com/87472110/131357960-b35c0951-795f-45fb-b61b-104abdc37823.jpg)

### Version of CR6Community Firmware

le dernier téléchargé ce jour 

### Printer model

Creality CR-6 SE

### Motherboard

Creality v4.5.3

### Display

Creality CR-6 stock touch screen

### Mods

rien

### Add-ons

rien

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by Sebazzz** [comment]
You flashed the wrong release probably - please retry.
