### ISSUE TITLE
Community Firmware 6.1 nozzle smashes into print surface

### ISSUE THREAD

**Issue by afmc1** [CR6Community/Marlin#279]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

When upgrading from version 5 to 6.1, when leveling the table, the nozzle goes against it and doesn't stop! I have to turn off the printer!
I had to re-install version 5 to get everything back to normal. My board is CR-ERA V1.1.0.3

### Version of CR6Community Firmware

5

### Printer model

Creality CR-6 SE

### Motherboard

Other (I will explain below)

### Display

Creality CR-6 stock touch screen

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ritchiedc** [comment]
Sounds like the optical sensor is plugged into the wrong port on the board. Creality and earlier versions of the community firmware were tolerant of this miss configuration and some printers came from the factory with it plugged into the wrong port. With board 4.5.3 it needs to plugged into J2 but the ERA board changed the names so I'm not sure which is the correct port.

Edit: After searching discord it looks like it needs to be in port J705. There is another possibility but if your only change was software version that one is unlikely.

**Comment by afmc1** [comment]
![board](https://user-images.githubusercontent.com/92735306/137781215-78b69f62-fc34-439e-ae22-1b33e1cc6b01.JPG)

**Comment by afmc1** [comment]
![IMG_4878](https://user-images.githubusercontent.com/92735306/137783513-6b752669-6a36-405a-97de-ca87eaf96ff7.JPG)

Port J705 is the second one, like on the 4.5.3.
I'll install 6.1 again to see if it works!

**Comment by ritchiedc** [comment]
Looks like it's plugged into the wrong port but the picture doesn't show all the markings because a cable is in the way. Looking at the board layout on Amazon I'd say it needs to be plugged into the second 3-pin connector from the left instead of the fourth connector.

By the way these are good questions to ask on the discord server.

**Comment by afmc1** [comment]
It works on port J705!! Thanks a lot for the help!

I asked the question here because I didn't know the most appropriate place.
Next time I know where to put!

**Comment by kds69** [comment]
Thank you so much guys!!
