### ISSUE TITLE
[FR] (First layer abl smoothing problem)

### ISSUE THREAD

**Issue by D4d092** [CR6Community/Marlin#288]
### Describe the feature you want

Hello,
I have a problem with my creality cr-6 if with motherboard 4.5.2 and firmware 6.1 relase after putting the firmware I reset the eprom as per procedure with M502 and M500.
the problem is that I have the convex bed or the center of the bed is closer to the nozzle and I have problems with the first layer, I notice that during the automatic leveling of only 16 points the probe does not touch the center of the plate.
I ask if it is possible to kindly have 32 leveling points to improve abl so that abl also touches the center of the bed and have a better first layer, also I notice that where the plate is lower it usually does not smooth out the first layer well lines do not merge as if abl does not level properly, currently using a z-offset of 0.12 an increase of abl points should solve the problem.
I hope you can help me Good Job.

**Comment by Sebazzz** [comment]
You can increase to the 7*7 (=49) leveling points of the CR-6 MAX by recompiling [the firmware yourself](https://damsteen.nl/blog/2021/01/08/how-to-compile-cr6community-marlin-with-vscode-platformio). Please ask in the Discord if you need any pointers. Good luck.
