### ISSUE TITLE
[FR] (hotend temperature increase)

### ISSUE THREAD

**Issue by D4d092** [CR6Community/Marlin#289]
### Describe the feature you want

Hello,
I have a creality cr-6 se with motherboard 4.5.2 firmware 6.1 relase, I have recently mounted hotend micro swiss all metal, kindly ask if you can increase the temperature up to 300 degrees to be able to print technical filaments.
Thanks Good job

**Comment by Sebazzz** [comment]
Sorry, I won't release any releases that need custom configuration like that, you [need to compile those yourself](https://damsteen.nl/blog/2021/01/08/how-to-compile-cr6community-marlin-with-vscode-platformio).

The reason for this is that all the combinations would significantly increase the number of builds to be done (N number of printers times M number of configurations).
