### ISSUE TITLE
[BUG] Bed Leveling temp issues 

### ISSUE THREAD

**Issue by Luk3du** [CR6Community/Marlin#297]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

Whenever doing ABL from the menu option, the temp sets correctly but shows as "0" when the z axis is moving and then goes back to the set temp after, this happens for every probe point 

### Bug Timeline

I did not notice this happening on stock fw, only on 6.1 community 

### Expected behavior

Temp stays on at all times 

### Actual behavior

Temp sets to 0 on z move during abl 

### Steps to Reproduce

"run automatic bed leveling" from leveling menu 

### Version of CR6Community Firmware

6.1 

### Printer model

Creality CR-6 SE

### Motherboard

Creality v1.1.0.0-ERA

### Display

Creality CR-6 stock touch screen

### Mods

No

### Add-ons

N/a

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by Thinkersbluff** [comment]
Have you read the readme file?

**Comment by Luk3du** [comment]
> Have you read the readme file?

Yes I read the readme files included in the 6.1 folder and the one on GitHub, haven't seen anything mentioning this anywhere?

**Comment by ritchiedc** [comment]
Just copied this from the faqs

"The temperatures go up/down/up/down while bed leveling

That is by design to improve bed leveling accuracy. You can turn that behaviour off by disabling "Better accuracy" in the leveling settings (not recommended)."

**Comment by Sebazzz** [comment]
Yup, it is mentioned and can be disabled as desired.
