### ISSUE TITLE
[FR] Add Option for disabling homing when printing shortly after a previous print

### ISSUE THREAD

**Issue by tobar-io** [CR6Community/Marlin#306]
### Describe the feature you want

If I want to print several objects in a row, it would be great if I could set that the print bed and nozzle do not cool down and that the homing can be skipped.

**Comment by Thinkersbluff** [comment]
Are you able to remove each print from the bed without moving the bed?

**Comment by tobar-io** [comment]
Not each, but smaller prints without brim pose no problem. Especially when I let it cool off.

But I see the problem with that. It's a niche case which can be adressed by octoprint plugins or via gcode.

**Comment by Thinkersbluff** [comment]
Ok to close this, then?

**Comment by tobar-io** [comment]
Yes, thanks.
