### ISSUE TITLE
Request for new firmware release

### ISSUE THREAD

**Issue by gbloice** [CR6Community/Marlin#324]
### Is your feature request related to a problem? Please describe.

It's been over a year since the last release and there have been many commits to Marlin and CR6-SE specific commits that aren't available to users unless they build their own firmware.

### Are you looking for hardware support?

Applies to all CR6 printers

### Describe the feature you want

A new release with the latest Marlin and CR6 updates.

**Comment by Thinkersbluff** [comment]
Please see the FAQs for the answer.
https://github.com/CR6Community/Marlin/wiki/Frequently-Asked-Questions-(FAQs)-about-the-CR6-Community-Firmware#are-there-any-plans-to-update-the-cf-beyond-version-61
