### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by kitu25** [CR6Community/Marlin#339]
### Is your feature request related to a problem? Please describe.

[HELP] after flashing the screen try to flash the motherboard but the screen beeps and the nozzle lights on. the screen shows the icons but does not show any number or letter. Sorry if the translation is not well understood but I don't speak English

### Are you looking for hardware support?

.

### Describe the feature you want

.

**Comment by Thinkersbluff** [comment]
This is not a troubleshooting forum and this is not a Feature Request.
Please join us in the Firmware Flashing channel of the Discord, to request help
