### ISSUE TITLE
[FR] Allow sorting of contents of SD Card by last modified date or alphabetical

### ISSUE THREAD

**Issue by apassiou** [CR6Community/Marlin#343]
### Describe the feature you want

Being able to sort by last modified date or alphabetically would make selection of prints easier.

**Comment by BloodyRain2k** [comment]
We already got 2 issues for this:
https://github.com/CR6Community/Marlin/issues/267
https://github.com/CR6Community/Marlin/issues/278

**Comment by Thinkersbluff** [comment]
Agreed.  No need to duplicate further.  Please contribute to one or both of those existing issues instead.
