### ISSUE TITLE
[FR] Support progress bar and file name when printing from host

### ISSUE THREAD

**Issue by Schallabajzr** [CR6Community/Marlin#55]
### Description

Support progress bar and filename when printing from host
### Feature Workflow

1. Connect host
2. Change the filename and progress % with a gcode command from host

#### Additional Information

If no such command exist maybe parse M117 command from DisplaylayerProgress OctoprintPlugin with the following format
[progress]% L=[current_layer]/[total_layers]

**Comment by Sebazzz** [comment]
This is supported via gcode M73 (issue #7 and #27) for progress in [release 4 alpha](https://github.com/CR6Community/Marlin/releases/tag/v2.0.7.1-cr6-community-release-4-alpha). 

File name is no gcode for, I think we should have a separate screen when printing from the host @grobux - without Resume/Stop buttons and only a button for going to the tune screen.

**Comment by Schallabajzr** [comment]
@Sebazzz Is there a standard way/plugin that can read hosts progress value and send it via M73?

**Comment by Sebazzz** [comment]
@Nushio would know that better than me.

**Comment by Schallabajzr** [comment]
I found this it supports print time genius https://plugins.octoprint.org/plugins/m73progress/

**Comment by Schallabajzr** [comment]
@Sebazzz got it working you can close the issue. Unless you want to keep it open for the separate print screen when printing from host.

**Comment by Sebazzz** [comment]
Not going for a separate screen now. 👍
