### ISSUE TITLE
Add PID tune and e steps to the touch screen [FR] (feature request title)

### ISSUE THREAD

**Issue by hughesjasonk** [CR6Community/Marlin#66]
### Feature Workflow

1. [First Action] adding PID tune to the touch screen
2. [Second Action] adding Estep setting to the touch screen
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Sebazzz** [comment]
Duplicate with #60 and #57
