### ISSUE TITLE
[BUG] Homing failed

### ISSUE THREAD

**Issue by giorgiomanieri** [CR6Community/Marlin#71]
### Bug Description

Home failed message during the homing after ABL

### Configuration Files

**Required:** Community firmware alpha 4

### Steps to Reproduce

1. Complete auto bed leveling
2. Start a print from Octoprint

**Expected behavior:**

**Actual behavior:**

After the bed leveling, the printer starts the homing and after that shows Home failed message. 
If I shutdown and turn on again before the starting print, the problem doesn't persists. 
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by Sebazzz** [comment]
Without logs I can't do anything. Are you running hotfix3?

**Comment by InsanityAutomation** [comment]
I have a code base here with the strain gauge and tare code refactored. Can you give my changes a try and see if its any more stable?

https://github.com/InsanityAutomation/Marlin/tree/CR-6Devel

**Comment by leyton01** [comment]
I am having this issue as well.

This seems to be the same issue as #67

**Comment by Sebazzz** [comment]
Can you try the changes from @InsanityAutomation ?

**Comment by MericasMeuth** [comment]
> Can you try the changes from @InsanityAutomation ?

Where do I find these changes?

**Comment by InsanityAutomation** [comment]
> 
> 
> > Can you try the changes from @InsanityAutomation ?
> 
> Where do I find these changes?

https://github.com/InsanityAutomation/Marlin/tree/CR-6Devel

**Comment by Sebazzz** [comment]
[Creality v4.5.2 motherboard firmware-crealityv452-20201223-002158.zip](https://github.com/CR6Community/Marlin/files/5732408/firmware-crealityv452-20201223-002158.zip)
[Creality v4.5.3 motherboard firmware-crealityv453-20201223-002246.zip](https://github.com/CR6Community/Marlin/files/5732406/firmware-crealityv453-20201223-002246.zip)
[Touch screen firmware CR-6-touchscreen-2020-12-23.zip](https://github.com/CR6Community/Marlin/files/5732436/CR-6-touchscreen-2020-12-23.zip)

Can you please retry this with one of these firmware files, depending on the motherboard version you have. If you don't know or got a printer from November 2020 or earlier, you'Il most likely have the Creality v4.5.2 motherboard. 

Assuming we got it fixed I will close this issue now and consider it fixed. If it isn't fixed please provide:
- Logs captured via Pronterface/Octoprint/PuTTY with `M111 S247` entered for debug logging
- Pictures or a video as appropriate

Also, if it is fixed, I still would like to have a confirmation though😀

**Comment by giorgiomanieri** [comment]
Solved for me

**Comment by leyton01** [comment]
Fixed for me in v5 pre-release
