### ISSUE TITLE
[FR] Please consider editing the default Configuration_adv.h file to prevent the Z axis from "dropping"

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/Marlin#72]
Configuration_adv.h allows users to set the automatic stepper release commands so that the Z axis does not drop on a print. 
I make a habit of setting that on my Ender-3, because that Z axis does drop freely when released.  I sometimes wonder whether one or the other Z-axis on my CR-6 may also be moving fractionally when motors are activated or released.  I do sometimes seem to have evidence of ABL performing badly as if the gantry is slightly "canted" to one side, for instance, yet other times all seems trammed & I have done nothing to the machine other than use it.

IF we find that our CR-6 Z-Offset/Probe issues are indeed influenced by the Z-axis dropping slightly, it might be a kindness to make this your default setting, when compiling releases for *.bin users:

In Configuration_adv.h, I change: #define DISABLE_INACTIVE_Z **true** to #define DISABLE_INACTIVE_Z **false**

/**
Idle Stepper Shutdown
Set DISABLE_INACTIVE_? 'true' to shut down axis steppers after an idle period.
The Deactive Time can be overridden with M18 and M84. Set to 0 for No Timeout.
*/
#define DEFAULT_STEPPER_DEACTIVE_TIME 120
#define DISABLE_INACTIVE_X true
#define DISABLE_INACTIVE_Y true
**#define DISABLE_INACTIVE_Z false // Set 'false' if the nozzle could fall onto your printed part!**
#define DISABLE_INACTIVE_E true
// If the Nozzle or Bed falls when the Z stepper is disabled, set its resting position here.
//#define Z_AFTER_DEACTIVATE Z_HOME_POS

AND I change the SD_FINISHED_RELEASECOMMAND to "M84XYE" from "M84", here:

**#define SD_FINISHED_STEPPERRELEASE true // Disable steppers when SD Print is finished**

**IF, however, there is a valid reason to NOT leave the Z motors activated for long periods (e.g. when folks leave their printers unattended for hours, even after the prints have finished)  then please disregard this FR and let me know!** 

Thanks.

**Comment by InsanityAutomation** [comment]
Typically this is only enabled on cartesian xy machines (corexy, hbot etc) with large beds that may cause damage if they drop. It's considered somewhat of a safety issue as the axis is locked in place and can't be moved by hand easily, as well as heating of both steppers and driver's. That said, it dropping is a sign of very good alignment ;) typically I tighten the rollers a bit to have it hold on idle.

**Comment by Sebazzz** [comment]
I suppose your proposal wouldn't hurt @Thinkersbluff - but I'm not sure what problem this would solve. Is it regarding leveling?

**Comment by Thinkersbluff** [comment]
My original thinking was to eliminate one more possibility for what might cause Z-Offset to change at random on only some machines.

At the time, I wondered whether Z might sometimes be dropping fractionally when the steppers were disabled.

It may not be a correct hypothesis, but it does seem like a simple way to cross that possibility off the list.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
