### ISSUE TITLE
Ability to Set default Led state on screen

### ISSUE THREAD

**Issue by Logicenios** [CR6Community/Marlin#79]
Hello, 

I would like to have the ability to change the default state of the led when the prints boots up because I am tired of turning it off manually. 

Thanks

**Comment by Sebazzz** [comment]
I think we should default to *off* and probably revert back to LED_CONTROL_PIN as well. In hindsight using the case light feature was a bad idea.

**Comment by Sebazzz** [comment]
Fixed in the latest `extui` rebased sources. Default to off.
