### ISSUE TITLE
[FR] Ability for the screen to go on sleep

### ISSUE THREAD

**Issue by Logicenios** [CR6Community/Marlin#80]
Hello, 

The official firmware has the ability for the screen to turn off after x seconds(which is bad because you can't change it anywhere) it you be useful having something like that.

Thanks

**Comment by Sebazzz** [comment]
I need to look further into the documentation of DGUS whether it is possible to set this dynamically. I'm afraid not though.

**Comment by Sebazzz** [comment]
![image](https://user-images.githubusercontent.com/1426097/102894626-b095f200-4463-11eb-8c5e-caa739c7fbeb.png)

It should be possible by writing to register 0x82.

**Comment by Sebazzz** [comment]
This is now implemented in the touch screen, temporary locations are here:

![image](https://user-images.githubusercontent.com/1426097/103097606-18853d80-4608-11eb-8004-122f9e921fe5.png)

@grobux is further refining the UX for this

Screen brightness is reduced to 10% on stand-by, and a mute function has been implemented.

**Comment by BubuMVX** [comment]
Screen updated, here's a preview:
![47_E_control](https://user-images.githubusercontent.com/2005901/103140540-fcf16400-46e7-11eb-8875-5efeefd7bbef.png)

**Comment by Sebazzz** [comment]
I'm closing this now because it has been implemented and is ready for CF5 beta. In addition, I've implemented a control for setting the screen stand-by brightness value. @grobux is doing the final UI polishing.
