### ISSUE TITLE
Filenames superimposed on home screen

### ISSUE THREAD

**Issue by ritchiedc** [CR6Community/Marlin#96]
### Description

When pressing "Print" home screen remains with filenames superimposed

### Steps to Reproduce

1. Fresh clone of CR6Community Marlin and CR-6-touchscreen on 27 Dec 2020
2. Build Marlin in VSCode and copy firmware in .pio\build to sd card
3. Build CR-6-touchscreen using build.cmd and copy contents of zip to micro sd card.
4. Turn off printer
5. Insert micro sd card with screen firmware, turn on printer and wait for "End!" (see screenshot).
6. Turn off printer
7. Remove micro sd card from screen and insert sd card with printer firmware
8. Turn on printer and wait for firmware to be written with home screen showing
9. Turn off printer
10. Remove sd card with fimware and insert sd card with gcode files.
11. Turn on printer
12. Press home screen print button.

**Expected behavior:** 

Display file list on

**Actual behavior:** 

File list is superimposed on home screen (see attached screenshot, sorry for the glare)

#### Additional Information

![PXL_20201227_155045266](https://user-images.githubusercontent.com/31545207/103174919-fd3e4c00-481a-11eb-9def-087e7bb9d0de.jpg)
![PXL_20201227_155154637](https://user-images.githubusercontent.com/31545207/103174925-03342d00-481b-11eb-8ca0-2540203c44f4.jpg)

**Comment by Sebazzz** [comment]
Your touch screen isn't flashed correctly. Note how the home screen doesn't contain the new designs of @grobux. Please retry flashing 2 more times.

**Comment by BubuMVX** [comment]
At step 3, make sure you are on the git branch `extui-dev` of the repo `CR6Community/CR-6-touchscreen`.

**Comment by ritchiedc** [comment]
Changing to the extui-dev branch worked. Thanks
